# Generated by Django 3.1 on 2020-08-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200818_1739'),
        ('posts', '0003_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(default=None, related_name='likes', to='profiles.Profile'),
        ),
    ]
