# Generated by Django 3.1 on 2020-09-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200818_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='User has no Bio!', max_length=500),
        ),
    ]
